DEFINES+=PROJECT_CONF_H=\"project-conf.h\"

CONTIKI_PROJECT = holliot-test
all: $(CONTIKI_PROJECT)


#SOURCES_DIR = ./sources

#REST_SOURCES_FILES += ctrl-flow.c gateway-mote-broadcast.c gateway-mote-runicast.c

#PROJECTDIRS += $(SOURCES_DIR)
#PROJECT_SOURCEFILES += $(REST_SOURCES_FILES)

##PROJECT_SOURCEFILES += test.c


CONTIKI = ../..

CONTIKI_WITH_RIME = 1
include $(CONTIKI)/Makefile.include
