CFLAGS += -DBOARD_SENSORTAG=1
CFLAGS += -DBACKDOOR_IOID=0x00000000

CONTIKI_TARGET_DIRS += sensortag common

BOARD_SOURCEFILES += sensortag-sensors.c  sensor-common.c
BOARD_SOURCEFILES += board.c board-i2c.c
BOARD_SOURCEFILES += am2320-sensor.c pir-sensor.c light-sensor.c
BOARD_SOURCEFILES += analog-temp-sensor.c ds18b20-temp-sensor.c
