DEFINES+=PROJECT_CONF_H=\"project-conf.h\"

CONTIKI_PROJECT = holliot-sensor-mote
all: $(CONTIKI_PROJECT)

#SOURCES_DIR = ./sources ./include

#REST_SOURCES_FILES += ctrl-flow.c sensor-mote-broadcast.c sensor-mote-runicast.c


#PROJECTDIRS += $(SOURCES_DIR)
#PROJECT_SOURCEFILES += $(REST_SOURCES_FILES)

##PROJECT_SOURCEFILES += sensor-mote.c



CONTIKI = ../..

CONTIKI_WITH_RIME = 1
CONTIKI_WITH_HOLLIOT_TERMINAL_MOTE = 1
include $(CONTIKI)/Makefile.include
